# Generated by Django 4.0.6 on 2022-08-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
